/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project_one;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;


@WebServlet("/home")
public class Library extends HttpServlet{
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    
    
    

}
