/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project_one;


import java.io.IOException;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;




@WebServlet("/login")
@MultipartConfig(location="/tmp",
    fileSizeThreshold = 1024,
    maxFileSize = 1024,
    maxRequestSize = 1024)
public class PrimaryServlet extends HttpServlet{
    /**
     *
     */
    private static final long serialVersionUID = -6668597909242177978L;

    private String url = "jdbc:postgresql://database-project-one.cjsdfjt5gj6o.us-east-1.rds.amazonaws.com:5432/projectone";
    private String uname = "nrevs";
    private String pwDB = "KTw6bEi8dy9vxGdRjfrM";

    private DBManager dbManager = new DBManager();
    final Logger logger = LogManager.getLogger(PrimaryServlet.class);


    public void init(ServletConfig config) throws ServletException {
        super.init(config);

    }

    private String loginId = "#maincontent";
    private String loginHtml = "" + 
        "<div>" +
            "<form id=\"loginform\" method=\"post\">" +
                "Username: <input type=\"text\" name=\"username\"/><br/><br/>" +
                "Password: <input type=\"password\" name=\"usrpass\"/><br/><br/>" +
                "<input type=\"submit\" value=\"login\"/><br/>" +
                "<a href=\"forgotuname\" onclick=\"forgotUsername()\">forgot username</a><br/>" +
                "<a href=\"forgotpass\" onclick=\"forgotPassword()\">forgot password</a><br/>" +
                "<a href=\"createaccount\" onclick=\"createAccount()\">create account</a><br/>" +
            "</form>" +
        "</div>";
    private String loginSrc = "login.js";
    private String loginCmpntId = "mainComponent";


    private String forgotUnHtml = "" +
        "" +
        "" +
        "" +
        "" +
        "" +
        "";
    private String forgotUnHtmlSrc = "forgotUn.js";

    private String forgotPwHtml = "" +
        "" +
        "" +
        "" +
        "" +
        "" +
        "";
    private String forgotPwHtmlSrc = "forgotPw.js";

    private String createHtml = "" +
        "" +
        "" +
        "" +
        "" +
        "" +
        "";
    private String createSrc = "create.js";

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse res) 
        throws ServletException,
                IOException 
    {
        String code = req.getParameter("code");
        logger.info("doGet -> request code: {}",code);

        HttpSession session = req.getSession();
        String uname = "username";
        if (session.getAttribute(uname)!=null) {
            String isadmin = "isadmin";
            if (session.getAttribute(isadmin)!=null) {
                req.getRequestDispatcher("/admin").forward(req, res);
            }
        }

        String rString = "";

        switch(code) {
            case "login":
                rString = setupResponseString(loginCmpntId, loginId, loginHtml, loginSrc);
                break;
            case "forgotUName":
                rString = setupResponseString(loginCmpntId, loginId, forgotUnHtml, forgotUnHtmlSrc);
                break;
            case "forgotPWord":
                rString = setupResponseString(loginCmpntId, loginId, forgotPwHtml, forgotPwHtmlSrc);
                break;
        }

        logger.info("doGet -> response string: {}", rString);

        if (rString != "") {
            res.setContentType("application/json");
            res.getWriter().println(rString);
        }
    }



    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse res) 
        throws ServletException,
                IOException
    {
        HttpSession session = req.getSession();

        String code = req.getParameter("code");
        logger.info("doPost -> request code: {}",code);

        try {
            JSONObject obj = JSONPartsHelper.getJSONParts(req.getParts());
            String username = obj.getString("username");
            String password = obj.getString("usrpass");
            
            System.out.println("Username: "+username);
            System.out.println("Password: "+password);



            try {
                Connection connection = DriverManager.getConnection(url, uname, pwDB);
                UserDAO userDAO = new UserDAO(connection);

                User usr = userDAO.getUser(username, password);
                if (usr != null) {
                    // User found and password checks out
                    logger.info("usr found");

                    session.setAttribute("username", usr.getUsername());
                    session.setAttribute("email", usr.getEmail());
                    session.setAttribute("id", usr.getId());

                    if(usr.isAdmin()) {
                        // user is admin
                        logger.info("admin user");

                        session.setAttribute("isadmin",true);

                        req.getRequestDispatcher("/admin").forward(req, res);


                    } else {
                        // user is NOT admin
                        logger.info("NOT admin user");
                        
                        req.getRequestDispatcher("/user").forward(req, res);

                    }
                } else {
                    // User password and/or username did not check out
                    logger.info("password or username invalid");
                    

                    Object aObj = session.getAttribute("loginattempts");
                    int a = 0;
                    if (aObj != null) {a  = (int)aObj;}
                    session.setAttribute("loginattempts",++a);
                    //TODO: invalid password or user response

                }

            } catch(SQLException sqlE) {
                sqlE.printStackTrace();
            }
        } catch(IOException ioE) {
            ioE.printStackTrace();
        }

        
    }
    
    private String setupResponseString(String componentId, String payloadId, String payloadHtml, String payloadSrc) {
        Payload payload = new Payload(payloadId, payloadHtml, payloadSrc);
        Component component = new Component(componentId, payload);
        
        RespObj rObj = new RespObj();
        rObj.addComponent(component);

        return JSON.toJSONString(rObj);
    }
    
}
