/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project_one;


import java.io.IOException;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;





@WebServlet("/api")
@MultipartConfig(location="/tmp",
    fileSizeThreshold = 1024,
    maxFileSize = 1024,
    maxRequestSize = 1024)
public class PrimaryServlet extends HttpServlet{
    /**
     *
     */
    private static final long serialVersionUID = -6668597909242177978L;
    private DBManager dbManager;

    public void init(ServletConfig config) throws ServletException {
        super.init(config);

        this.dbManager = new DBManager();
    }

    private String loginId = "#maincontent";
    private String loginHtml = "" + 
        "<div>" +
            "<form id=\"loginform\" method=\"post\">" +
                "Username: <input type=\"text\" name=\"username\"/><br/><br/>" +
                "Password: <input type=\"password\" name=\"usrpass\"/><br/><br/>" +
                "<input type=\"submit\" value=\"login\"/><br/>" +
                "<a href=\"forgotuname\" onclick=\"forgotUsername()\">forgot username</a><br/>" +
                "<a href=\"forgotpass\" onclick=\"forgotPassword()\">forgot password</a><br/>" +
                "<a href=\"createaccount\" onclick=\"createAccount()\">create account</a><br/>" +
            "</form>" +
        "</div>";
    private String loginSrc = "login.js";
    private String loginCmpntId = "mainComponent";
    
    

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse res) 
        throws ServletException,
                IOException 
    {
        String code = req.getParameter("code");
        System.out.println("doGet: "+code);

        Payload payload = new Payload(loginId, loginHtml, loginSrc);
        Component loginCmp = new Component(loginCmpntId, payload);
        
        RespObj rObj = new RespObj();
        rObj.addComponent(loginCmp);

        
        String rString = JSON.toJSONString(rObj);
        System.out.println("Response String: "+rString);


        switch(code) {
            case "login":
                res.setContentType("application/json");
                res.getWriter().println(rString);
                break;
        }
    }



    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse res) 
        throws ServletException,
                IOException
        {
            String code = req.getParameter("code");
            System.out.println("doPost: "+code);

            try {
                JSONObject obj = JSONPartsHelper.getJSONParts(req.getParts());
                String username = obj.getString("username");
                String password = obj.getString("usrpass");
                
                System.out.println("Username: "+username);
                System.out.println("Password: "+password);
                //this.dbManager = new DBManager();
                //boolean r = this.dbManager.userDAO.validate(username, password);
                //System.out.println(String.valueOf(r));


                String url = "jdbc:postgresql://database-project-one.cjsdfjt5gj6o.us-east-1.rds.amazonaws.com:5432/projectone";
                String uname = "nrevs";
                String pwDB = "KTw6bEi8dy9vxGdRjfrM";
                try {
                    Connection connection = DriverManager.getConnection(url, uname, pwDB);
                    System.out.println("-1");
                    UserDAO userDAO = new UserDAO(connection);
                    System.out.println("-2");
                    boolean r = userDAO.validate(username, password);
                    if (r) {

                    } else {

                    }

                } catch(SQLException sqlE) {
                    System.out.println("-3");
                    sqlE.printStackTrace();
                }
            } catch(IOException ioE) {
                ioE.printStackTrace();
            }

            
        }
    

    

}
